
-- 1. **Find the top 5 customers who have spent the most money overall.**
--    * Show their full name and total amount spent.
--    * Sort from highest to lowest.
SELECT CONCAT(c.first_name, ' ', c.last_name) AS "Full Name", SUM(i.total) AS "Total Amount Spent"
FROM customer c
JOIN invoice i
ON c.customer_id = i.customer_id
GROUP BY "Full Name"
ORDER BY "Total Amount Spent" DESC;


-- 2. **Show the total revenue generated by each music genre.**
--    * Include the genre name and total revenue.
--    * Order by revenue descending
SELECT g.name AS "Genre", SUM(i.unit_price * i.quantity) AS "total revenue"
FROM genre g 
JOIN track t
ON g.genre_id = t.genre_id
JOIN invoice_line i 
ON t.track_id = i.track_id
GROUP BY "Genre"
ORDER BY "total revenue" DESC;


-- 3. **Find customers who have purchased tracks from at least 4 different genres.**
--    * Show the customer's name and the number of unique genres they've bought.

-- SELECT CONCAT(c.first_name, ' ', c.last_name) AS "Full Name", 
-- 4. **For each artist, find their best-selling album.**

--    * Show the artist name, album name, and total revenue generated by that album.
--    * Each artist should appear only once.

-- 5. **Rank customers by total spending within their own country.**

--    * Show customer name, country, total spent, and their rank in that country.

